# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml sonar:sonar -Dsonar.projectKey=codingcasters -Dsonar.host.url=http://40.76.86.164:9000 -Dsonar.login=435364985ee2370aa0ddfb2678a29f34737b3dd7

    - name: Target
      uses: actions/upload-artifact@v2
      with:
        name: Artifact and Files
        path: /home/runner/work/githubactions/githubactions/target
